### ISSUE TITLE
esp32-s3-box touch functionality locks up after touching red circle (home) button

### ISSUE THREAD

**Issue by PaulskPt** [adafruit/Adafruit_CircuitPython_TT21100#2]
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-beta.2 on 2023-04-26; ESP32-S3-Box-2.5 with ESP32S3
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2022 Paulus Schulinck
#
# SPDX-License-Identifier: MIT
##############################
# 2022-10-22. Last update: 2023-07-26
# by @PaulskPt
#
# touch test results on an Espressif ESP32-S3-BOX
#
#        319        X          0
#         |                    |
#      ---+--------------------+--- 0
#         |                    |
#         |                    |
#         |                    |
#   Y     |                    |             Middle: x: 159, y: 119
#         |                    |
#         |                    |
#         |                    |
#      ---+--------------------+--- 239
#         |                    |
#
# Conclusion: instead of having 0,0 as the top-left corner
#             the top-right corner is 0,0
#             and the lower-left is 319,239
# NOTE: touching the "red" button on the middle of the lower part of the display
#       causes the touch functionality to halt. Only a reset can restart the
#       touch test again. This problem I will discuss with the Adafruit Circuitpython team.
#
"""
    Example output (part):
        Circuitpython ESP32-S3-Box touch test.
        Please touch the screen,
        except the bottom line with the red button dot.
        main():
        Waiting for your touches...

        ck_touch(): nr of touches= 1
        ck_touched(): screen touched at: (319,0). Pressure: 13
        main(): Added touch data: id= 0, at x,y = 319,0. Pressure= 13
        [...]
        There are 10 records in the touch dictionary:
        dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
        key:  0, x,y =   0,  0. id:   0. pressure: 0
        key:  1, x,y = 221,129. id:   0. pressure: 26
        key:  2, x,y = 221,129. id:   0. pressure: 34
        key:  3, x,y = 152, 94. id:   0. pressure: 32
        key:  4, x,y = 238, 36. id:   0. pressure: 26
        key:  5, x,y = 280, 56. id:   0. pressure: 30
        key:  6, x,y = 179, 95. id:   0. pressure: 47
        key:  7, x,y =  25,191. id:   0. pressure: 25
        key:  8, x,y =  57, 45. id:   0. pressure: 25
        key:  9, x,y = 319,  0. id:   0. pressure: 13
        Done!
"""
####
import time
import sys

touch_dict = {0: {'x':0,
                'y': 0,
                'id': 0,
                'pressure': 0}}

import board
import busio
import adafruit_tt21100

my_debug = False

i2c = busio.I2C(board.SCL, board.SDA)

# Create library object (named "tt") using a Bus I2C port
# Note: GPIO3 is connected to board.CPT_INT
#       See schematic -> Strapping
tt = adafruit_tt21100.TT21100(i2c) # , irq_pin=3)
# print(f"dir(tt)= {dir(tt)}")
if tt:
    if my_debug:
        print(f"\ndir(tt)= {dir(tt)}")
    print(f"Global: tt._i2c= {tt._i2c}, irq_pin= {tt._irq_pin}")

touch_x = 0
touch_y = 0
touch_id = 0  # this is used in case of multi-touch
touch_pr = 0

def clr_touch():
    global touch_x, touch_y, touch_id, touch_pr, tt
    touch_x = 0
    touch_y = 0
    touch_id = 0
    touch_pr = 0

    # Clear the touch buffer
    TAG="clr_touch(): "
    cnt = 0
    ts = []
    while True:
        ts = tt.touches
        if my_debug:
            print(TAG+f"ts= {ts}, type(ts)= {type(ts)}")
        if isinstance(ts, list):
            if len(ts) == 0:
                break
        if cnt == 0:
            time.sleep(0.2)
        cnt += 1
        if cnt >= 10:
            if not my_debug:
                print(TAG+f"touch buffer read {cnt} times.")
            break

def ck_touch():
    TAG = "ck_touch(): "
    # if the screen is being touched print the touches
    ts = None
    n = tt.touched
    if n > 0:
        print(TAG+f"nr of touches= {n}")
        ts = tt.touches
        if my_debug:
            print(f"type(ts)= {type(ts)}")
        print(f"ck_touched(): screen touched at: ({ts[0]['x']},{ts[0]['y']}). Pressure: {ts[0]['pressure']}")
    return ts

def main():
    global touch_x, touch_y, touch_id, touch_pr
    TAG = "main(): "
    cnt = 0  # index to touch_dict
    ts = None
    print("\nCircuitpython ESP32-S3-Box touch test.")
    print("Please touch the screen,")
    print("except the bottom line with the red button dot.")
    print(TAG+"\nWaiting for your touches...\n")
    clr_touch()
    while True:
        try:
            while ts is None:
                ts = ck_touch()  # added just for trial
                if ts is None:
                    time.sleep(1)
            t = type(ts)
            if isinstance(ts, list):
                ts_dict = ts[0]
                t = type(ts_dict)
                # print(TAG+f"type(ts_dict)= {t}")
                if isinstance(ts_dict, dict):
                    touch_y = ts_dict['y']
                    touch_x = ts_dict['x']
                    touch_id = ts_dict['id']
                    touch_pr = ts_dict['pressure']
                    if cnt in touch_dict.keys():
                        cnt += 1  # we don't want overwrite existing touch data
                    touch_dict[cnt] = {'x': touch_x, 'y': touch_y, 'id': touch_id, 'pressure': touch_pr}
                    print(TAG+f"Added touch data: id= {touch_id}, at x,y = {touch_x},{touch_y}. Pressure= {touch_pr}")
                    # cleanup for next round
                    clr_touch()
                    ts = None
                    # increase dict key index
                    cnt += 1
                else:
                    print(TAG+f"expected type dict but received type: {t}")
                    raise TypeError
            else:
                print(TAG+f"expected type list but received type: {t}")
                raise TypeError

        except KeyboardInterrupt:
            print("User interrupted. Exiting...")
            break

        time.sleep(1)
        if cnt >= 10:
            break

    le = len(touch_dict)
    if le > 0:
        print(f"\nThere are {le} records in the touch dictionary:")
        print(touch_dict.keys())
        try:
            for k,v in touch_dict.items():
                print("key: {:2d}, x,y = {:3d},{:3d}. id: {:3d}. pressure: {}".format(k, v['x'],
                    v['y'], v['id'], v['pressure']))
        except IndexError as e:
            print(f"IndexError occurred at key= {k}")
    else:
        print("touch dictionary is empty")
    print("Done!\n")
    sys.exit()


if __name__ == '__main__':
    main()


REPL output of board:
>>> import board
>>> dir(board)
['__class__', '__name__', 'BOOT', 'CLK', 'CS', 'CTP_INT', 'DISPLAY', 'G10', 'G11', 'G12', 'G13', 'G14', 'G21', 'G38', 'G39', 'G40', 'G41', 'G42', 'G43', 'G44', 'G9', 'I2S_ADC_SDOUT', 'I2S_CODEC_DSDIN', 'I2S_LRCK', 'I2S_MCLK', 'I2S_SCLK', 'LCD_CS', 'LCD_CTRL', 'LCD_DC', 'LCD_MOSI', 'LCD_RST', 'LCD_SCK', 'MISO', 'MOSI', 'MUTE_STATUS', 'PA_CTRL', 'SCL', 'SCL2', 'SDA', 'SDA2', 'U0RXD', 'U0TXD', 'board_id']
```

### Behavior

The script above runs fine until the "red" circle button in the middle on the bottom of the frame around the display is touched (see image in ´Additional information´ below.
Only a reset of the device can restore the touch functionality.

### Description

See also the closed issue adafruit/circuitpython#7095.

### Additional information

Adafruit product: https://www.adafruit.com/product/5290

In documation of Espressif the "red" button is referred as "home" button.
The Espressif demo firmware makes use of the "red" circle button.

On the ESPHome website (https://esphome.io/components/touchscreen/tt21100.html),
there is a paragraph named "Binary Sensor". The text is as follows:
"Binary Sensor
In addition to touch areas on the screen configured through the [Touchscreen](https://esphome.io/components/touchscreen/index.html#config-touchscreen) component, the TT21100 supports up to four buttons located outside of the normal touchscreen area. On the ESP32-S3-BOX and the ESP32-S3-Korvo-2-LCD, the red circle below the display is such a button. A binary sensor can be configured to react to touching these buttons."

In circuitpython 8.1.0-beta.2 in the board module there is no "board.HOME" button defined.

Question:
-----------
Is there a way to program the "red" circle button for use within Circuitpython,
and to resolve the locking up of touch functionality after touching the "red" circle button?

![2023-07-26_ESP32-S3-Box_CPY_script_home_button_problem](https://github.com/adafruit/circuitpython/assets/9107950/986f9789-e088-4789-99d4-a0b6b6dbc43e)

**Comment by dhalbert** [comment]
I don't think this is a CircuitPython core bug. There would be no `board.HOME` because the red "button" is just an area on the touch screen. There might also be a separate pin on the touch controller for these special areas, but I've been unable to find a datasheet for the TT21100 yet. Moving this issue to the library repo.

**Comment by dhalbert** [comment]
@tekktrik Do you have a pointer to the datasheet? The documentation for the Box seems to only be https://github.com/espressif/esp-box

**Comment by dhalbert** [comment]
@tannewt Looks like you wrote the initial version of the library. Do you have a pointer to the datasheet for the touch controller, or did you glean the specs from the Espressif code? The documentation for the Box seems to only be https://github.com/espressif/esp-box

**Comment by PaulskPt** [comment]
Espressif (ESPRegistry) does have a touch component for the esp32-s3:  https://components.espressif.com/components/espressif/esp_lcd_touch

**Comment by PaulskPt** [comment]
Updated cpy to: Adafruit CircuitPython 8.2.1 on 2023-07-25; ESP32-S3-Box-2.5 with ESP32S3. 
Same result

**Comment by PaulskPt** [comment]
![20230726_154302](https://github.com/adafruit/Adafruit_CircuitPython_TT21100/assets/9107950/39067ec7-5ed7-4c09-a2b7-b0ecb48d3e0a)

**Comment by dhalbert** [comment]
> Espressif (ESPRegistry) does have a touch component for the esp32-s3: https://components.espressif.com/components/espressif/esp_lcd_touch

We don't use that, since this is an I2C device we can talk to. Otherwise we'd have to write special C code for this particular board. Nevertheless, it may provide clues if there is no datasheet.

**Comment by dhalbert** [comment]
I'm confused. Your code is written to get ten results and then finish. If you touched the red button at, say, touch 4, what would happen?

**Comment by PaulskPt** [comment]
If I touch the red button at touch 4 then the next touch(es) are not "seen". It seems that the device is locked up.

**Comment by dhalbert** [comment]
Could you add some print statements to see what is going on? Is `ck_touch()` only returning None inside the loop, or is CircuitPython literally not running?

**Comment by PaulskPt** [comment]
Yes,

**Comment by PaulskPt** [comment]
I modified ck_touch(). I also added a global var "touch_iter". I discovered that the script is running. See the new script listing in the top of this issue.
After an iteration when the red button is touched, the result of any subsequent touches on the display is resulting in 0.

REPL output:

Circuitpython ESP32-S3-Box touch test.
Please touch the screen,
except the bottom line with the red button dot.
main(): 
Waiting for your touches...

ck_touch(): Touch iteration: 1. Nr touch(es)= 0
ck_touch(): Touch iteration: 2. Nr touch(es)= 0
ck_touch(): Touch iteration: 3. Nr touch(es)= 0
ck_touch(): Touch iteration: 4. Nr touch(es)= 0
ck_touch(): Touch iteration: 5. Nr touch(es)= 0
ck_touch(): nr of touches= 1
ck_touch(): screen touched at: (70,129). Pressure: 22
main(): Added touch data: id= 0, at x,y = 70,129. Pressure= 22
ck_touch(): Touch iteration: 7. Nr touch(es)= 0
ck_touch(): nr of touches= 1
ck_touch(): screen touched at: (159,103). Pressure: 54
main(): Added touch data: id= 0, at x,y = 159,103. Pressure= 54
ck_touch(): Touch iteration: 9. Nr touch(es)= 0
ck_touch(): nr of touches= 1
ck_touch(): screen touched at: (72,145). Pressure: 56
main(): Added touch data: id= 0, at x,y = 72,145. Pressure= 56
ck_touch(): Touch iteration: 11. Nr touch(es)= 0
ck_touch(): Touch iteration: 12. Nr touch(es)= 0
ck_touch(): Touch iteration: 13. Nr touch(es)= 0
ck_touch(): Touch iteration: 14. Nr touch(es)= 0
ck_touch(): Touch iteration: 15. Nr touch(es)= 0
ck_touch(): Touch iteration: 16. Nr touch(es)= 0
ck_touch(): Touch iteration: 17. Nr touch(es)= 0
User interrupted. Exiting...

There are 4 records in the touch dictionary:
dict_keys([0, 1, 2, 3])
key:  0, x,y =   0,  0. id:   0. pressure: 0
key:  1, x,y =  70,129. id:   0. pressure: 22
key:  2, x,y = 159,103. id:   0. pressure: 54
key:  3, x,y =  72,145. id:   0. pressure: 56
Done!

]0;🐍Wi-Fi: off | Done | 8.2.1\
Code done running.

NOTES: the first 5 iterations no touches were done. Next I did three touches (iterations 7, 9 and 11). Then I touched the red button.
The next iterations, while touching the dispay, the result was "Nr touch(es)= 0".

**Comment by PaulskPt** [comment]
I connected desktop PC with PuTTY to the serial output of the ESP32-S3-Box. via a serial-to-USB converter. At reset the output is as follows:

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2a (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x15d8
load:0x403b6000,len:0xbf8
load:0x403ba000,len:0x31c8
entry 0x403b621c
I (25) boot: ESP-IDF v4.4.3 2nd stage bootloader
I (25) boot: compile time 02:05:18
I (25) boot: chip revision: 0
I (26) qio_mode: Enabling default flash chip QIO
I (32) boot.esp32s3: Boot SPI Speed : 80MHz
I (36) boot.esp32s3: SPI Mode       : QIO
I (41) boot.esp32s3: SPI Flash Size : 16MB
I (46) boot: Enabling RNG early entropy source...
I (51) boot: Partition Table:
I (55) boot: ## Label            Usage          Type ST Offset   Length
I (62) boot:  0 nvs              WiFi data        01 02 00009000 00005000
I (70) boot:  1 otadata          OTA data         01 00 0000e000 00002000
I (77) boot:  2 ota_0            OTA app          00 10 00010000 00200000
I (85) boot:  3 ota_1            OTA app          00 11 00210000 00200000
I (92) boot:  4 uf2              factory app      00 00 00410000 00040000
I (100) boot:  5 ffat             Unknown data     01 81 00450000 00bb0000
I (107) boot: End of partition table
I (611) esp_image: segment 0: paddr=00010020 vaddr=3c110020 size=2d568h (185704)                                                                       map
I (644) esp_image: segment 1: paddr=0003d590 vaddr=3fc9b420 size=02a88h ( 10888)                                                                       load
I (646) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=10d678h (110348                                                                      0) map
I (817) esp_image: segment 3: paddr=0014d6a0 vaddr=3fc9dea8 size=01a60h (  6752)                                                                       load
I (819) esp_image: segment 4: paddr=0014f108 vaddr=40374000 size=17418h ( 95256)                                                                       load
I (841) esp_image: segment 5: paddr=00166528 vaddr=600fe000 size=0102ch (  4140)                                                                       load
I (852) boot: Loaded app from partition at offset 0x10000
I (852) boot: Disabling RNG early entropy source...

**Comment by PaulskPt** [comment]
In the Espressif demo sources for the ESP32-S3-Box I found the definition for the "Home" button and some use of it in files of the domo. See the screenshots below:

![Espressif_ESP32-S3-Box_demo_bsp_board h_Home_button](https://github.com/adafruit/Adafruit_CircuitPython_TT21100/assets/9107950/f7877c0a-08dc-4f16-8b3d-bea5f5b68d49)


![Espressif_ESP32-S3-Box_demo_about_us_Home_button](https://github.com/adafruit/Adafruit_CircuitPython_TT21100/assets/9107950/dbf58555-6984-4fe1-8147-7b9686e793cd)



![Espressif_ESP32-S3-Box_demo_ui_player_Home_button](https://github.com/adafruit/Adafruit_CircuitPython_TT21100/assets/9107950/aa1f8288-5e5b-435a-9084-e56720e747e0)

**Comment by PaulskPt** [comment]
Problem solved:
I discovered the following:
a) pressing the red circle button lowers the board.CTP_INT line as does any display touch.
In my script I defined board.CTP_INT as global digitalio object 'touch_int''.
The board.CTP_INT line can be cleared by calling clr_touch() which empties the the touches buffer by reading it until no more list of touches is present.
b) after pressing the red circle button, when calling ck_touch, the tt.touched value will be 0. In that case if also the board.CTP_INT line is False (Low), then it must be that a virtual button, in this case, the red circle button has been pressed. I added a global flag 'red_circle_flag'. In ck_touch() this flag will be set in the case of board.CTP_INT is False and tt.touched is 0. Next, in main() the status of red_circle_flag will be tested. If True, the user will be informed via REPL, next a sys.exit() will be called, causing the script to exit. In this case the red circle button functions as a KeybardInterrrupt. Naturally we can do other things than that.

Proof (REPL output):

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;🐍Wi-Fi: off | code.py | 8.2.1\Global: tt._i2c= <I2CDevice>, irq_pin= None
init(): touch_int.value= False

Circuitpython ESP32-S3-Box touch test.
Please touch the screen,
except the bottom line with the red button dot.
main(): 
Waiting for your touches...

ck_touch(): touch iteration: 1. Nr touch(es)= 0
ck_touch(): touch iteration: 2. Nr touch(es)= 0
ck_touch(): touch iteration: 3. Nr touch(es)= 0
ck_touch(): nr of touches= 1
ck_touch(): screen touched at: (97,114). Pressure: 41
main(): Added touch data: id= 0, at x,y = 97,114. Pressure= 41
ck_touch(): touch iteration: 5. Nr touch(es)= 0
ck_touch(): touch iteration: 6. Nr touch(es)= 0
ck_touch(): touch iteration: 7. Nr touch(es)= 0
ck_touch(): touch iteration: 8. Nr touch(es)= 0
ck_touch(): red_circle_flag set. Value= True
ck_touch(): touch buffer cleared. Status of CTP_INT= True
main(): red circle button has been pressed. Exiting...
]0;🐍Wi-Fi: off | Done | 8.2.1\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
]0;🐍Wi-Fi: off | REPL | 8.2.1\
Adafruit CircuitPython 8.2.1 on 2023-07-25; ESP32-S3-Box-2.5 with ESP32S3
